# Public release version for reproducible academic testing.
"""
PCB drill-bit allocation with CSV-driven production, inventory, policy, and hole-rule settings
============================================================================================

This version reads four CSV files from the folder `drill_qubo_csv_templates`
placed next to this .py file:

1. production_plan_template.csv
2. drill_inventory_template_corrected.csv
3. daily_policy_template.csv
4. hole_regrind_rule_template.csv

The fourth CSV controls which regrind levels are allowed for each hole type.
Example:
    A: R0E
    B: R0N, R1, R2
    C: R0E, R0N, R1, R2, R3

Important modeling notes
------------------------
- R0E is treated as a new-drill first-life usage.
- Every physical R0E bit generates an R0N continuation capacity after first life.
- R0N allocations share that continuation capacity.
- R0E/R0N/R1/R2/R3 capacity_hits are read from drill_inventory_template_corrected.csv.
- R1/R2/R3 counts are computed from total assigned units divided by CSV-driven capacity units.
- Inventory available_count is now used in two ways:
  (1) common post-evaluation metrics for all policies;
  (2) an optimization-time overuse penalty for balanced_dynamic, so the proposed
      method actively avoids exceeding available_count - min_reserve_count.

Compared policies
-----------------
- efficiency_first
- static_cost_first
- dynamic_preference_greedy
- balanced_no_preference
- balanced_dynamic

Outputs are written to `drill_bit_csv_dynamic_output/`.
"""

from __future__ import annotations

import argparse
import itertools
import math
import random
import time
from pathlib import Path
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd


# ============================================================
# Settings
# ============================================================

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_TEMPLATE_DIR = SCRIPT_DIR / "drill_qubo_csv_templates"
OUTPUT_DIR = SCRIPT_DIR / "drill_bit_csv_dynamic_output"

UNIT_HITS = 250

DEFAULT_CAP_UNITS = {
    "R0E": 1,   # fallback: 250 hits, first-life new drill
    "R0N": 11,  # fallback: 2750 hits, continuation capacity generated by R0E bits
    "R1": 12,   # fallback: 3000 hits
    "R2": 8,    # fallback: 2000 hits
    "R3": 4,    # fallback: 1000 hits
}

# Runtime capacity units. In V3 this is overwritten from drill_inventory_template.csv
# using the capacity_hits column. Values are expressed in UNIT_HITS units.
CAP_UNITS = DEFAULT_CAP_UNITS.copy()

COST_LEVEL_MAP = {
    "R0E": "R0",
    "R0N": "R0",
    "R1": "R1",
    "R2": "R2",
    "R3": "R3",
}

FALLBACK_BASE_COST_WEIGHTS = {
    "R0": 5.0,
    "R1": 3.0,
    "R2": 1.8,
    "R3": 0.8,
}

MIN_DYNAMIC_COST = 0.2

RANDOM_SEARCH_ITER = 80
SA_SEQUENCE_STEPS = 200
SA_SEQUENCE_RESTARTS = 3
SA_T0 = 50.0
SA_T_END = 0.01
RANDOM_SEED = 42
# Exhaustive search is used only for small job sets. For 6+ jobs, V3 uses random/SA search
# because CSV-driven capacity and inventory-aware allocation expands the candidate space.
MAX_EXHAUSTIVE_PN_COUNT = 6

DUE_STEP_PENALTY_SCALE = 100.0

EVAL_W_CHANGE = 1.0
EVAL_W_COST = 1.0
EVAL_W_DUE = 1.0
EVAL_W_INVENTORY_OVERUSE = 10.0

# Optimization-time inventory overuse penalty for balanced_dynamic.
# This must be much larger than normal tool-change/cost terms so inventory
# feasibility is treated as an active optimization constraint rather than
# only a soft post-evaluation warning. If a zero-overuse candidate exists,
# balanced_dynamic will strongly prefer it. If no zero-overuse candidate
# exists, it will choose the candidate with the smallest overuse first,
# then optimize cost/tool changes.
OPT_W_INVENTORY_OVERUSE = 1_000_000.0

HOLE_TYPES = ["A", "B", "C"]
REGRIND_LEVELS = ["R0E", "R0N", "R1", "R2", "R3"]
COUNT_LEVELS = ["R0", "R1", "R2", "R3"]


# ============================================================
# Utility
# ============================================================

def ceil_div(a: int, b: int) -> int:
    return (a + b - 1) // b


def to_units(hits: int) -> int:
    if hits % UNIT_HITS != 0:
        raise ValueError(
            f"Hits {hits} is not divisible by UNIT_HITS={UNIT_HITS}. "
            f"Please make sure hole counts are multiples of {UNIT_HITS}."
        )
    return hits // UNIT_HITS


def clean_str_value(v) -> Optional[str]:
    if pd.isna(v):
        return None
    s = str(v).strip()
    if s == "" or s.lower() in ["nan", "none", "null"]:
        return None
    return s


def as_float(row: pd.Series, col: str, default: float) -> float:
    if col not in row or pd.isna(row[col]):
        return float(default)
    return float(row[col])


def resolve_default_path(filename: str) -> Path:
    return DEFAULT_TEMPLATE_DIR / filename


def read_csv_with_validation(path: Path, required_cols: List[str], name: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Cannot find {name} CSV: {path}")
    df = pd.read_csv(path)
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"{name} CSV is missing columns: {missing}. File: {path}")
    return df


# ============================================================
# Inventory / capacity helpers for V3
# ============================================================

def inventory_level_to_count_level(level: str) -> str:
    """Map inventory-level labels to physical count buckets.

    R0E and R0N both belong to the physical R0 bucket. R0N is generated
    continuation life and should not be treated as independent stock.
    """
    level = str(level).upper().strip()
    if level in ["R0", "R0E", "R0N"]:
        return "R0"
    return level


def default_capacity_hits(level: str) -> int:
    level = str(level).upper().strip()
    if level == "R0":
        level = "R0E"
    return int(DEFAULT_CAP_UNITS.get(level, 1) * UNIT_HITS)


def inventory_row_for_count_level(inventory_df: pd.DataFrame, count_level: str) -> pd.Series:
    """Return the stock row used for inventory availability by count level."""
    count_level = str(count_level).upper().strip()
    if count_level == "R0":
        sub = inventory_df[inventory_df["regrind_level"] == "R0E"]
    else:
        sub = inventory_df[inventory_df["regrind_level"] == count_level]
    if len(sub) == 0:
        return pd.Series({"available_count": 0, "min_reserve_count": 0})
    return sub.iloc[0]


def build_capacity_units(inventory_df: pd.DataFrame) -> Dict[str, int]:
    """Build CAP_UNITS from CSV capacity_hits.

    capacity_hits must be divisible by UNIT_HITS. R0N may be inventory_mode=generated;
    its capacity still controls continuation capacity generated by R0E usage.
    """
    cap: Dict[str, int] = DEFAULT_CAP_UNITS.copy()
    for _, row in inventory_df.iterrows():
        level = str(row["regrind_level"]).upper().strip()
        if level not in REGRIND_LEVELS:
            continue
        hits = int(row.get("capacity_hits", default_capacity_hits(level)))
        if hits <= 0:
            hits = default_capacity_hits(level)
        if hits % UNIT_HITS != 0:
            raise ValueError(
                f"capacity_hits for {level} must be divisible by UNIT_HITS={UNIT_HITS}. Got {hits}."
            )
        cap[level] = hits // UNIT_HITS
    for level in REGRIND_LEVELS:
        cap.setdefault(level, DEFAULT_CAP_UNITS[level])
    return cap


# ============================================================
# CSV loading
# ============================================================

def load_production_plan(path: Path) -> pd.DataFrame:
    required = ["pn", "panels", "A_per_panel", "B_per_panel", "C_per_panel"]
    df = read_csv_with_validation(path, required, "production plan")

    if "batch_id" not in df.columns:
        df["batch_id"] = df["pn"].astype(str)
    if "due_priority" not in df.columns:
        df["due_priority"] = 0
    if "fixed_sequence" not in df.columns:
        df["fixed_sequence"] = np.nan
    if "remark" not in df.columns:
        df["remark"] = ""

    numeric_cols = ["panels", "A_per_panel", "B_per_panel", "C_per_panel", "due_priority"]
    for c in numeric_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0).astype(int)

    df["fixed_sequence"] = pd.to_numeric(df["fixed_sequence"], errors="coerce")

    if (df["panels"] <= 0).any():
        bad = df.loc[df["panels"] <= 0, ["pn", "batch_id", "panels"]]
        raise ValueError(f"Panels must be positive. Bad rows:\n{bad}")

    df["job_id"] = df["pn"].astype(str) + "|" + df["batch_id"].astype(str)
    return df


def load_inventory(path: Path) -> pd.DataFrame:
    """Load drill inventory and drill-life specification.

    V3 accepts the preferred format:
        regrind_level,available_count,min_reserve_count,capacity_hits,
        base_cost_weight,priority_consume,shortage_risk,inventory_mode,remark

    Recommended rows:
        R0E: stock row, first-life new drill, e.g. capacity_hits=250
        R0N: generated row, continuation life, e.g. capacity_hits=2750
        R1/R2/R3: stock rows with their own capacity_hits

    Backward compatibility:
        If an old R0 row is provided, it is expanded into R0E and R0N.
    """
    required = ["regrind_level", "available_count"]
    df = read_csv_with_validation(path, required, "drill inventory")
    df = df.copy()

    defaults = {
        "base_cost_weight": np.nan,
        "priority_consume": 0,
        "shortage_risk": 0,
        "min_reserve_count": 0,
        "capacity_hits": np.nan,
        "inventory_mode": "stock",
        "remark": "",
    }
    for col, default in defaults.items():
        if col not in df.columns:
            df[col] = default

    df["regrind_level"] = df["regrind_level"].astype(str).str.upper().str.strip()
    df["inventory_mode"] = df["inventory_mode"].fillna("stock").astype(str).str.lower().str.strip()

    # Backward compatibility for old R0 row.
    old_r0 = df[df["regrind_level"] == "R0"]
    extra_rows = []
    if len(old_r0) > 0:
        r0 = old_r0.iloc[0].to_dict()
        if not (df["regrind_level"] == "R0E").any():
            r0e = dict(r0)
            r0e["regrind_level"] = "R0E"
            r0e["capacity_hits"] = default_capacity_hits("R0E")
            r0e["inventory_mode"] = "stock"
            r0e["remark"] = "auto-expanded from old R0 row as R0E"
            extra_rows.append(r0e)
        if not (df["regrind_level"] == "R0N").any():
            r0n = dict(r0)
            r0n["regrind_level"] = "R0N"
            r0n["available_count"] = 0
            r0n["min_reserve_count"] = 0
            r0n["capacity_hits"] = default_capacity_hits("R0N")
            r0n["base_cost_weight"] = 0.0
            r0n["inventory_mode"] = "generated"
            r0n["remark"] = "auto-expanded from old R0 row as generated R0N"
            extra_rows.append(r0n)
    if extra_rows:
        df = pd.concat([df, pd.DataFrame(extra_rows)], ignore_index=True)

    # Keep only new explicit inventory levels.
    df = df[df["regrind_level"].isin(REGRIND_LEVELS)].copy()

    # Numeric conversions. Blank values are treated as 0 for stock counts and default for capacity/cost.
    for c in ["available_count", "priority_consume", "shortage_risk", "min_reserve_count"]:
        df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0).astype(int)
    df["base_cost_weight"] = pd.to_numeric(df["base_cost_weight"], errors="coerce")
    df["capacity_hits"] = pd.to_numeric(df["capacity_hits"], errors="coerce")

    rows = []
    for level in REGRIND_LEVELS:
        sub = df[df["regrind_level"] == level]
        if len(sub) == 0:
            # Auto-add missing row using safe defaults.
            count_level = inventory_level_to_count_level(level)
            rows.append({
                "regrind_level": level,
                "available_count": 0,
                "base_cost_weight": 0.0 if level == "R0N" else FALLBACK_BASE_COST_WEIGHTS.get(count_level, 1.0),
                "priority_consume": 0,
                "shortage_risk": 1 if level != "R0N" else 0,
                "min_reserve_count": 0,
                "capacity_hits": default_capacity_hits(level),
                "inventory_mode": "generated" if level == "R0N" else "stock",
                "remark": "auto-added missing row",
            })
        else:
            row = sub.iloc[0].to_dict()
            if pd.isna(row.get("capacity_hits", np.nan)) or int(row.get("capacity_hits", 0)) <= 0:
                row["capacity_hits"] = default_capacity_hits(level)
            count_level = inventory_level_to_count_level(level)
            if pd.isna(row.get("base_cost_weight", np.nan)):
                row["base_cost_weight"] = 0.0 if level == "R0N" else FALLBACK_BASE_COST_WEIGHTS.get(count_level, 1.0)
            if level == "R0N":
                row["inventory_mode"] = "generated"
                # R0N is generated by R0E usage; it is not independent warehouse stock.
                row["available_count"] = 0
                row["min_reserve_count"] = 0
            rows.append(row)

    out = pd.DataFrame(rows)
    out["capacity_hits"] = pd.to_numeric(out["capacity_hits"], errors="coerce").fillna(0).astype(int)
    for _, row in out.iterrows():
        hits = int(row["capacity_hits"])
        level = str(row["regrind_level"])
        if hits <= 0 or hits % UNIT_HITS != 0:
            raise ValueError(
                f"capacity_hits for {level} must be positive and divisible by UNIT_HITS={UNIT_HITS}. Got {hits}."
            )
    return out

def load_daily_policy(path: Path) -> pd.Series:
    required = ["policy_name", "active", "w_change", "w_cost"]
    df = read_csv_with_validation(path, required, "daily policy")

    defaults = {
        "w_due": 1.0,
        "w_inventory": 1.0,
        "w_capacity": 1.0,
        "w_quality": 1e9,
        "preferred_regrind": None,
        "preference_strength": 0.0,
        "remark": "",
    }
    for col, default in defaults.items():
        if col not in df.columns:
            df[col] = default

    active = df[pd.to_numeric(df["active"], errors="coerce").fillna(0).astype(int) == 1]
    if len(active) == 0:
        print("WARNING: No active daily policy found. Using the first policy row.")
        row = df.iloc[0].copy()
    elif len(active) > 1:
        print("WARNING: Multiple active daily policies found. Using the first active row.")
        row = active.iloc[0].copy()
    else:
        row = active.iloc[0].copy()

    for c in ["w_change", "w_cost", "w_due", "w_inventory", "w_capacity", "w_quality", "preference_strength"]:
        row[c] = float(pd.to_numeric(row[c], errors="coerce")) if not pd.isna(row[c]) else defaults.get(c, 0.0)

    pref = clean_str_value(row.get("preferred_regrind", None))
    row["preferred_regrind"] = pref.upper() if pref else None
    return row


def load_hole_regrind_rules(path: Path) -> Tuple[Dict[str, List[str]], pd.DataFrame]:
    """Load hole-type to allowed-regrind rules from CSV.

    Required columns:
        hole_type,regrind_level,allowed

    Example rows:
        A,R0E,1
        B,R0N,1
        B,R1,1
        B,R2,1
        C,R0E,1
        C,R0N,1
        C,R1,1
        C,R2,1
        C,R3,1
    """
    required = ["hole_type", "regrind_level", "allowed"]
    df = read_csv_with_validation(path, required, "hole regrind rule")
    df = df.copy()
    df["hole_type"] = df["hole_type"].astype(str).str.upper().str.strip()
    df["regrind_level"] = df["regrind_level"].astype(str).str.upper().str.strip()
    df["allowed"] = pd.to_numeric(df["allowed"], errors="coerce").fillna(0).astype(int)

    df = df[df["hole_type"].isin(HOLE_TYPES) & df["regrind_level"].isin(REGRIND_LEVELS)].copy()

    rules: Dict[str, List[str]] = {}
    for hole in HOLE_TYPES:
        allowed = df[(df["hole_type"] == hole) & (df["allowed"] == 1)]["regrind_level"].tolist()
        if not allowed:
            raise ValueError(f"hole_regrind_rule CSV has no allowed regrind level for hole type {hole}.")
        rules[hole] = allowed

    return rules, df


# ============================================================
# Data preparation and cost weights
# ============================================================

def prepare_pn_table_from_df(plan_df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, item in plan_df.iterrows():
        pn = str(item["pn"])
        batch_id = str(item.get("batch_id", pn))
        job_id = str(item.get("job_id", f"{pn}|{batch_id}"))
        panels = int(item["panels"])
        A = int(item["A_per_panel"]) * panels
        B = int(item["B_per_panel"]) * panels
        C = int(item["C_per_panel"]) * panels
        total = A + B + C

        rows.append({
            "job_id": job_id,
            "pn": pn,
            "batch_id": batch_id,
            "panels": panels,
            "due_priority": int(item.get("due_priority", 0)),
            "fixed_sequence": item.get("fixed_sequence", np.nan),
            "remark": item.get("remark", ""),

            "A_holes": A,
            "B_holes": B,
            "C_holes": C,
            "A_units": to_units(A) if A > 0 else 0,
            "B_units": to_units(B) if B > 0 else 0,
            "C_units": to_units(C) if C > 0 else 0,
            "A_ratio": A / max(total, 1),
            "B_ratio": B / max(total, 1),
            "C_ratio": C / max(total, 1),
        })
    return pd.DataFrame(rows)


def build_base_cost_weights(inventory_df: pd.DataFrame) -> Dict[str, float]:
    """Build physical-count cost weights from inventory rows.

    R0 cost is taken from R0E because R0N is generated continuation life and
    should not define independent R0 stock/cost.
    """
    weights: Dict[str, float] = {}
    for _, row in inventory_df.iterrows():
        level = str(row["regrind_level"]).upper()
        if level == "R0N":
            continue
        count_level = inventory_level_to_count_level(level)
        if count_level not in COUNT_LEVELS:
            continue
        base = row.get("base_cost_weight", np.nan)
        if pd.isna(base):
            base = FALLBACK_BASE_COST_WEIGHTS[count_level]
        weights[count_level] = float(base)
    for r in COUNT_LEVELS:
        weights.setdefault(r, FALLBACK_BASE_COST_WEIGHTS[r])
    return weights

def build_dynamic_cost_weights(inventory_df: pd.DataFrame, policy: pd.Series) -> Tuple[Dict[str, float], pd.DataFrame]:
    """Build dynamic cost by physical count level and report row-level details.

    R0 dynamic cost is based on R0E. R0N is generated continuation capacity, so
    it is included in the report but does not overwrite the R0 cost.
    """
    w_inventory = as_float(policy, "w_inventory", 1.0)
    policy_prefer = policy.get("preferred_regrind", None)
    policy_strength = as_float(policy, "preference_strength", 0.0)

    rows = []
    weights: Dict[str, float] = {}

    for _, row in inventory_df.iterrows():
        level = str(row["regrind_level"]).upper()
        count_level = inventory_level_to_count_level(level)
        base = row.get("base_cost_weight", np.nan)
        if pd.isna(base):
            base = 0.0 if level == "R0N" else FALLBACK_BASE_COST_WEIGHTS[count_level]
        base = float(base)

        priority_consume = int(row.get("priority_consume", 0))
        shortage_risk = int(row.get("shortage_risk", 0))
        available = int(row.get("available_count", 0))
        reserve = int(row.get("min_reserve_count", 0))
        inventory_mode = str(row.get("inventory_mode", "stock")).lower().strip()
        capacity_hits = int(row.get("capacity_hits", default_capacity_hits(level)))

        consume_discount = w_inventory * 0.45 * priority_consume
        shortage_penalty = w_inventory * 0.75 * shortage_risk
        reserve_penalty = w_inventory * 0.75 if inventory_mode != "generated" and available <= reserve else 0.0
        policy_discount = policy_strength if policy_prefer in [level, count_level] else 0.0

        dynamic = max(MIN_DYNAMIC_COST, base - consume_discount - policy_discount + shortage_penalty + reserve_penalty)

        # Do not let R0N overwrite R0; R0 cost is defined by R0E physical stock.
        if level != "R0N" and count_level in COUNT_LEVELS:
            weights[count_level] = dynamic

        rows.append({
            "regrind_level": level,
            "count_level": count_level,
            "inventory_mode": inventory_mode,
            "capacity_hits": capacity_hits,
            "base_cost_weight": base,
            "available_count": available,
            "min_reserve_count": reserve,
            "priority_consume": priority_consume,
            "shortage_risk": shortage_risk,
            "consume_discount": consume_discount,
            "policy_discount": policy_discount,
            "shortage_penalty": shortage_penalty,
            "reserve_penalty": reserve_penalty,
            "dynamic_cost_weight": dynamic,
        })

    for r in COUNT_LEVELS:
        weights.setdefault(r, FALLBACK_BASE_COST_WEIGHTS[r])
    return weights, pd.DataFrame(rows)

def build_inventory_allowed_counts(inventory_df: pd.DataFrame) -> Dict[str, int]:
    """Allowed physical bit counts after reserving safety stock.

    R0 availability comes from R0E stock. R0N is generated continuation capacity
    and is not treated as independent inventory.
    """
    allowed: Dict[str, int] = {r: 0 for r in COUNT_LEVELS}
    for _, row in inventory_df.iterrows():
        level = str(row["regrind_level"]).upper()
        if level == "R0N":
            continue
        count_level = inventory_level_to_count_level(level)
        if count_level not in COUNT_LEVELS:
            continue
        inventory_mode = str(row.get("inventory_mode", "stock")).lower().strip()
        if inventory_mode == "generated":
            continue
        available = int(row.get("available_count", 0))
        reserve = int(row.get("min_reserve_count", 0))
        allowed[count_level] = max(0, available - reserve)
    return allowed

def incremental_inventory_overuse(
    counts: Dict[str, int],
    used_counts_before: Optional[Dict[str, int]],
    inventory_allowed_counts: Optional[Dict[str, int]],
) -> Tuple[int, Dict[str, int]]:
    """Compute incremental overuse caused by this candidate allocation.

    The incremental form avoids double-counting overuse across production steps.
    For each level:
        before_over = max(0, used_before - allowed)
        after_over  = max(0, used_before + candidate_count - allowed)
        incremental = after_over - before_over
    """
    per_level: Dict[str, int] = {r: 0 for r in COUNT_LEVELS}
    if used_counts_before is None or inventory_allowed_counts is None:
        return 0, per_level

    total = 0
    for r in COUNT_LEVELS:
        before = int(used_counts_before.get(r, 0))
        add = int(counts.get(r, 0))
        allowed = int(inventory_allowed_counts.get(r, 0))
        before_over = max(0, before - allowed)
        after_over = max(0, before + add - allowed)
        inc = max(0, after_over - before_over)
        per_level[r] = int(inc)
        total += int(inc)
    return int(total), per_level


def make_no_preference_policy() -> pd.Series:
    return pd.Series({
        "policy_name": "balanced_no_preference",
        "preferred_regrind": None,
        "w_change": 1.0,
        "w_cost": 1.0,
        "w_due": 0.0,
        "w_inventory": 0.0,
        "w_capacity": 1.0,
        "w_quality": 1e9,
        "preference_strength": 0.0,
    })


def get_step_policy(step: int, policy: pd.Series, cost_weights: Dict[str, float]) -> Dict:
    return {
        "step_phase": str(policy.get("policy_name", "active_policy")),
        "prefer": policy.get("preferred_regrind", None),
        "w_change": as_float(policy, "w_change", 1.0),
        "w_cost": as_float(policy, "w_cost", 1.0),
        "w_due": as_float(policy, "w_due", 1.0),
        "w_capacity": as_float(policy, "w_capacity", 1.0),
        "w_quality": as_float(policy, "w_quality", 1e9),
        "cost_weights": cost_weights,
    }


def cost_for(regrind: str, cost_weights: Dict[str, float]) -> float:
    return float(cost_weights[COST_LEVEL_MAP[regrind]])


def capacity_for(regrind: str) -> int:
    return int(CAP_UNITS[regrind])


# ============================================================
# Allocation evaluation
# ============================================================

def all_allocation_keys() -> List[str]:
    return [f"{h}_{r}" for h in HOLE_TYPES for r in REGRIND_LEVELS]


def normalize_alloc(alloc: Dict[str, int]) -> Dict[str, int]:
    return {k: max(0, int(alloc.get(k, 0))) for k in all_allocation_keys()}


def count_physical_bits(a: Dict[str, int]) -> Dict[str, int]:
    units_by_level = {r: 0 for r in REGRIND_LEVELS}
    for h in HOLE_TYPES:
        for r in REGRIND_LEVELS:
            units_by_level[r] += int(a.get(f"{h}_{r}", 0))

    r0e_units = units_by_level["R0E"]
    counts = {
        "R0": ceil_div(r0e_units, CAP_UNITS["R0E"]) if r0e_units > 0 else 0,
        "R1": ceil_div(units_by_level["R1"], CAP_UNITS["R1"]) if units_by_level["R1"] > 0 else 0,
        "R2": ceil_div(units_by_level["R2"], CAP_UNITS["R2"]) if units_by_level["R2"] > 0 else 0,
        "R3": ceil_div(units_by_level["R3"], CAP_UNITS["R3"]) if units_by_level["R3"] > 0 else 0,
    }
    return counts


def evaluate_pn_allocation(
    row: pd.Series,
    step: int,
    alloc: Dict[str, int],
    policy_name: str,
    order_name: str,
    cost_weights: Dict[str, float],
    w_change: float,
    w_cost: float,
    w_due: float,
    w_capacity: float,
    w_quality: float,
    step_phase: str,
    preferred_regrind: str | None,
    rules: Dict[str, List[str]],
    use_due_priority: bool = True,
    used_counts_before: Optional[Dict[str, int]] = None,
    inventory_allowed_counts: Optional[Dict[str, int]] = None,
    w_inventory_overuse_optimization: float = 0.0,
) -> Tuple[Dict, Dict]:
    a = normalize_alloc(alloc)
    demand_units = {h: int(row[f"{h}_units"]) for h in HOLE_TYPES}

    unmet_units = 0
    quality_violation_count = 0

    for h in HOLE_TYPES:
        assigned = 0
        for r in REGRIND_LEVELS:
            val = a.get(f"{h}_{r}", 0)
            assigned += val
            if val > 0 and r not in rules[h]:
                quality_violation_count += val
        unmet_units += abs(demand_units[h] - assigned)

    counts = count_physical_bits(a)
    tool_change_count = counts["R0"] + counts["R1"] + counts["R2"] + counts["R3"]

    r0n_used = sum(a.get(f"{h}_R0N", 0) for h in HOLE_TYPES)
    r0n_capacity = counts["R0"] * CAP_UNITS["R0N"]
    r0n_over = max(0, r0n_used - r0n_capacity)
    over_capacity_count = 1 if r0n_over > 0 else 0

    relative_cost_score = (
        cost_weights["R0"] * counts["R0"]
        + cost_weights["R1"] * counts["R1"]
        + cost_weights["R2"] * counts["R2"]
        + cost_weights["R3"] * counts["R3"]
    )

    raw_due_priority = int(row.get("due_priority", 0))
    due_priority = raw_due_priority if use_due_priority else 0
    due_penalty = due_priority * max(0, step - 1) * DUE_STEP_PENALTY_SCALE

    opt_overuse_count, opt_overuse_by_level = incremental_inventory_overuse(
        counts=counts,
        used_counts_before=used_counts_before,
        inventory_allowed_counts=inventory_allowed_counts,
    )
    optimization_inventory_overuse_penalty = (
        float(w_inventory_overuse_optimization) * float(opt_overuse_count)
    )

    objective_score = (
        w_change * tool_change_count
        + w_cost * relative_cost_score
        + w_due * due_penalty
        + optimization_inventory_overuse_penalty
        + w_quality * quality_violation_count
        + w_capacity * 1e9 * over_capacity_count
        + w_capacity * 1e9 * unmet_units
    )

    result = {
        "order_name": order_name,
        "policy_name": policy_name,
        "step": step,
        "job_id": row["job_id"],
        "pn": row["pn"],
        "batch_id": row["batch_id"],
        "due_priority": due_priority,
        "raw_due_priority": raw_due_priority,
        "fixed_sequence": row.get("fixed_sequence", np.nan),
        "step_phase": step_phase,
        "preferred_regrind": preferred_regrind if preferred_regrind is not None else "None",
        "w_change": w_change,
        "w_cost": w_cost,
        "w_due": w_due,
        "w_capacity": w_capacity,
        "cost_R0": cost_weights["R0"],
        "cost_R1": cost_weights["R1"],
        "cost_R2": cost_weights["R2"],
        "cost_R3": cost_weights["R3"],
        "R0_count": counts["R0"],
        "R1_count": counts["R1"],
        "R2_count": counts["R2"],
        "R3_count": counts["R3"],
        "tool_change_count": tool_change_count,
        "R0N_capacity_hits": r0n_capacity * UNIT_HITS,
        "R0N_used_hits": r0n_used * UNIT_HITS,
        "R0N_unused_hits": max(0, r0n_capacity - r0n_used) * UNIT_HITS,
        "relative_cost_score": relative_cost_score,
        "due_penalty": due_penalty,
        "objective_score": objective_score,
        "quality_violation_count": quality_violation_count,
        "over_capacity_count": over_capacity_count,
        "unmet_units": unmet_units,
        "optimization_inventory_overuse_count": int(opt_overuse_count),
        "optimization_inventory_overuse_penalty": float(optimization_inventory_overuse_penalty),
        "optimization_inventory_overuse_R0": int(opt_overuse_by_level["R0"]),
        "optimization_inventory_overuse_R1": int(opt_overuse_by_level["R1"]),
        "optimization_inventory_overuse_R2": int(opt_overuse_by_level["R2"]),
        "optimization_inventory_overuse_R3": int(opt_overuse_by_level["R3"]),
    }

    for h in HOLE_TYPES:
        result[f"{h}_hits"] = demand_units[h] * UNIT_HITS
        for r in REGRIND_LEVELS:
            result[f"{h}_{r}_hits"] = a.get(f"{h}_{r}", 0) * UNIT_HITS

    return result, a


# ============================================================
# Rule-based allocation policies
# ============================================================

def allocate_r0e_fixed(row: pd.Series, rules: Dict[str, List[str]]) -> Dict[str, int]:
    """Allocate each hole type that only allows R0E to R0E.

    This keeps Type A behavior compatible with the old model when A only allows R0E.
    """
    alloc: Dict[str, int] = {}
    for h in HOLE_TYPES:
        if rules[h] == ["R0E"]:
            alloc[f"{h}_R0E"] = int(row[f"{h}_units"])
    return alloc


def fill_remaining_by_single_choice(row: pd.Series, alloc: Dict[str, int], rules: Dict[str, List[str]], choice_func) -> Dict[str, int]:
    out = dict(alloc)
    r0n_capacity = count_physical_bits(normalize_alloc(out))["R0"] * CAP_UNITS["R0N"]
    r0n_used = sum(out.get(f"{h}_R0N", 0) for h in HOLE_TYPES)

    for h in HOLE_TYPES:
        demand = int(row[f"{h}_units"])
        already = sum(out.get(f"{h}_{r}", 0) for r in REGRIND_LEVELS)
        rem = max(0, demand - already)
        if rem == 0:
            continue

        # Use R0N first if allowed, because it consumes continuation capacity.
        if "R0N" in rules[h]:
            use0 = min(rem, max(0, r0n_capacity - r0n_used))
            if use0 > 0:
                out[f"{h}_R0N"] = out.get(f"{h}_R0N", 0) + use0
                rem -= use0
                r0n_used += use0

        if rem > 0:
            choices = [r for r in rules[h] if r != "R0N"]
            if not choices:
                # infeasible by rules; leave unmet so evaluator penalizes it.
                continue
            r = choice_func(choices)
            out[f"{h}_{r}"] = out.get(f"{h}_{r}", 0) + rem
    return out


def allocation_efficiency_first(row: pd.Series, rules: Dict[str, List[str]]) -> Dict[str, int]:
    """Use R0N first, then the allowed level with largest capacity."""
    base = allocate_r0e_fixed(row, rules)

    def largest_capacity(choices: List[str]) -> str:
        return max(choices, key=lambda r: (capacity_for(r), -cost_for(r, FALLBACK_BASE_COST_WEIGHTS)))

    return fill_remaining_by_single_choice(row, base, rules, largest_capacity)


def allocation_static_cost_first(row: pd.Series, rules: Dict[str, List[str]], base_cost_weights: Dict[str, float]) -> Dict[str, int]:
    """Use R0N first, then the allowed level with the lowest base cost."""
    base = allocate_r0e_fixed(row, rules)

    def cheapest_base(choices: List[str]) -> str:
        return min(choices, key=lambda r: cost_for(r, base_cost_weights))

    return fill_remaining_by_single_choice(row, base, rules, cheapest_base)


def allocation_dynamic_preference_greedy(row: pd.Series, rules: Dict[str, List[str]], cost_weights: Dict[str, float]) -> Dict[str, int]:
    """Use R0N first, then the allowed level with the lowest dynamic cost."""
    base = allocate_r0e_fixed(row, rules)

    def cheapest_dynamic(choices: List[str]) -> str:
        return min(choices, key=lambda r: cost_for(r, cost_weights))

    return fill_remaining_by_single_choice(row, base, rules, cheapest_dynamic)


def split_candidates(rem: int, choices: List[str]) -> List[Dict[str, int]]:
    """Generate candidate splits for remaining units across allowed regrinds.

    Kept intentionally compact to avoid exploding exhaustive sequence search.
    """
    choices = list(dict.fromkeys(choices))
    if rem <= 0:
        return [{}]
    if not choices:
        return [{}]
    if len(choices) == 1:
        return [{choices[0]: rem}]

    candidates: List[Dict[str, int]] = []

    # all-in-one choices
    for r in choices:
        candidates.append({r: rem})

    # pair splits to give balanced_dynamic real alternatives
    fractions = [0.25, 0.5, 0.75]
    for i, r1 in enumerate(choices):
        for r2 in choices[i + 1:]:
            for f in fractions:
                u1 = int(round(rem * f))
                u2 = rem - u1
                candidates.append({r1: u1, r2: u2})

    # one equal split among all choices
    base = rem // len(choices)
    d = {r: base for r in choices}
    d[choices[-1]] += rem - sum(d.values())
    candidates.append(d)

    # de-duplicate
    seen = set()
    out = []
    for c in candidates:
        c = {r: int(v) for r, v in c.items() if int(v) > 0}
        key = tuple(sorted(c.items()))
        if key not in seen:
            seen.add(key)
            out.append(c)
    return out


def allocation_balanced_dynamic(
    row: pd.Series,
    rules: Dict[str, List[str]],
    cost_weights: Dict[str, float],
    active_policy: pd.Series,
    policy_name: str,
    used_counts_before: Optional[Dict[str, int]] = None,
    inventory_allowed_counts: Optional[Dict[str, int]] = None,
    w_inventory_overuse_optimization: float = 0.0,
) -> Dict[str, int]:
    """QUBO-inspired candidate search using the hole-rule CSV.

    It searches feasible-like splits under the allowed hole/regrind rules and
    chooses the allocation with the lowest internal objective.
    """
    best_score = float("inf")
    best_alloc: Optional[Dict[str, int]] = None

    # Start from hole types that are forced to R0E only.
    forced = allocate_r0e_fixed(row, rules)

    # Hole types still to optimize.
    variable_holes = [h for h in HOLE_TYPES if not (rules[h] == ["R0E"])]

    # Generate R0E candidate use for variable holes if allowed.
    r0e_options: Dict[str, List[int]] = {}
    for h in variable_holes:
        units = int(row[f"{h}_units"])
        if "R0E" in rules[h]:
            r0e_options[h] = sorted(set([0, units // 4, units // 2, units]))
        else:
            r0e_options[h] = [0]

    # Product over R0E choices for variable hole types.
    r0e_keys = variable_holes
    r0e_products = itertools.product(*(r0e_options[h] for h in r0e_keys)) if r0e_keys else [()]

    step_policy = get_step_policy(1, active_policy, cost_weights)

    for r0e_vals in r0e_products:
        base_alloc = dict(forced)
        for h, val in zip(r0e_keys, r0e_vals):
            if val > 0:
                base_alloc[f"{h}_R0E"] = val

        r0_count = count_physical_bits(normalize_alloc(base_alloc))["R0"]
        r0n_cap = r0_count * CAP_UNITS["R0N"]

        # R0N allocation candidates per variable hole type, sequentially.
        def recurse_r0n(idx: int, alloc_so_far: Dict[str, int], cap_left: int):
            if idx >= len(variable_holes):
                yield alloc_so_far
                return
            h = variable_holes[idx]
            demand = int(row[f"{h}_units"])
            assigned = sum(alloc_so_far.get(f"{h}_{r}", 0) for r in REGRIND_LEVELS)
            rem = max(0, demand - assigned)
            if rem <= 0 or "R0N" not in rules[h]:
                yield from recurse_r0n(idx + 1, alloc_so_far, cap_left)
                return

            opts = sorted(set([0, min(rem, cap_left), min(rem, cap_left // 2)]))
            for use0 in opts:
                new_alloc = dict(alloc_so_far)
                if use0 > 0:
                    new_alloc[f"{h}_R0N"] = new_alloc.get(f"{h}_R0N", 0) + use0
                yield from recurse_r0n(idx + 1, new_alloc, cap_left - use0)

        for alloc_after_r0n in recurse_r0n(0, base_alloc, r0n_cap):
            # Split remaining units for each variable hole among allowed non-R0N/non-R0E regrinds.
            split_lists = []
            split_holes = []
            infeasible = False
            for h in variable_holes:
                demand = int(row[f"{h}_units"])
                assigned = sum(alloc_after_r0n.get(f"{h}_{r}", 0) for r in REGRIND_LEVELS)
                rem = max(0, demand - assigned)
                if rem == 0:
                    continue
                choices = [r for r in rules[h] if r not in ["R0E", "R0N"]]
                if not choices:
                    infeasible = True
                    break
                split_holes.append(h)
                split_lists.append(split_candidates(rem, choices))
            if infeasible:
                continue

            for split_product in itertools.product(*split_lists) if split_lists else [()]:
                alloc = dict(alloc_after_r0n)
                for h, split in zip(split_holes, split_product):
                    for r, v in split.items():
                        alloc[f"{h}_{r}"] = alloc.get(f"{h}_{r}", 0) + int(v)

                summary, _ = evaluate_pn_allocation(
                    row=row,
                    step=1,
                    alloc=alloc,
                    policy_name=policy_name,
                    order_name="candidate",
                    cost_weights=cost_weights,
                    w_change=step_policy["w_change"],
                    w_cost=step_policy["w_cost"],
                    w_due=0.0,
                    w_capacity=step_policy["w_capacity"],
                    w_quality=step_policy["w_quality"],
                    step_phase="candidate",
                    preferred_regrind=step_policy["prefer"],
                    rules=rules,
                    use_due_priority=False,
                    used_counts_before=used_counts_before,
                    inventory_allowed_counts=inventory_allowed_counts,
                    w_inventory_overuse_optimization=w_inventory_overuse_optimization,
                )

                if summary["objective_score"] < best_score:
                    best_score = summary["objective_score"]
                    best_alloc = alloc

    if best_alloc is None:
        return allocation_efficiency_first(row, rules)
    return best_alloc


# ============================================================
# Sequence helpers
# ============================================================

def get_original_sequence(pn_df: pd.DataFrame) -> List[str]:
    return pn_df["job_id"].astype(str).tolist()


def get_due_priority_first_sequence(pn_df: pd.DataFrame) -> List[str]:
    return pn_df.sort_values(["due_priority", "A_holes", "C_holes"], ascending=[False, False, True])["job_id"].astype(str).tolist()


def get_high_A_first_sequence(pn_df: pd.DataFrame) -> List[str]:
    return pn_df.sort_values(["A_holes", "C_holes"], ascending=[False, True])["job_id"].astype(str).tolist()


def get_high_C_first_sequence(pn_df: pd.DataFrame) -> List[str]:
    return pn_df.sort_values(["C_holes", "A_holes"], ascending=[False, False])["job_id"].astype(str).tolist()


def get_high_C_last_sequence(pn_df: pd.DataFrame) -> List[str]:
    return pn_df.sort_values(["C_holes", "A_holes"], ascending=[True, False])["job_id"].astype(str).tolist()


def get_fixed_sequence_candidate(pn_df: pd.DataFrame) -> List[str]:
    fixed = pn_df[pn_df["fixed_sequence"].notna()].sort_values("fixed_sequence")
    free = pn_df[pn_df["fixed_sequence"].isna()].sort_values(["due_priority", "A_holes"], ascending=[False, False])
    return pd.concat([fixed, free], ignore_index=True)["job_id"].astype(str).tolist()


def enforce_fixed_positions(seq: List[str], pn_df: pd.DataFrame, ignore_fixed: bool = False) -> List[str]:
    if ignore_fixed:
        return list(seq)
    fixed_rows = pn_df[pn_df["fixed_sequence"].notna()].copy()
    if len(fixed_rows) == 0:
        return seq

    n = len(seq)
    output = [None] * n
    fixed_ids = set()

    for _, row in fixed_rows.sort_values("fixed_sequence").iterrows():
        pos = int(row["fixed_sequence"])
        pos = max(1, min(n, pos)) - 1
        job = str(row["job_id"])
        if output[pos] is None:
            output[pos] = job
            fixed_ids.add(job)

    remaining = [j for j in seq if j not in fixed_ids]
    k = 0
    for i in range(n):
        if output[i] is None:
            output[i] = remaining[k]
            k += 1
    return [str(x) for x in output]


def get_free_jobs_for_search(pn_df: pd.DataFrame, ignore_fixed: bool = False) -> List[str]:
    if ignore_fixed:
        return pn_df["job_id"].astype(str).tolist()
    return pn_df[pn_df["fixed_sequence"].isna()]["job_id"].astype(str).tolist()


def make_sequence_from_free_order(pn_df: pd.DataFrame, free_order: List[str], ignore_fixed: bool = False) -> List[str]:
    if ignore_fixed:
        return list(free_order)
    base_fixed = pn_df[pn_df["fixed_sequence"].notna()].sort_values("fixed_sequence")["job_id"].astype(str).tolist()
    seq = base_fixed + list(free_order)
    return enforce_fixed_positions(seq, pn_df, ignore_fixed=False)


# ============================================================
# Sequence simulation and search
# ============================================================

def simulate_sequence(
    pn_df: pd.DataFrame,
    sequence: List[str],
    order_name: str,
    policy_name: str,
    active_policy: pd.Series,
    cost_weights: Dict[str, float],
    base_cost_weights: Dict[str, float],
    rules: Dict[str, List[str]],
    inventory_allowed_counts: Optional[Dict[str, int]] = None,
) -> Tuple[Dict, pd.DataFrame]:
    pn_map = {str(row["job_id"]): row for _, row in pn_df.iterrows()}
    is_pure_baseline = policy_name == "balanced_no_preference"
    sequence = enforce_fixed_positions(sequence, pn_df, ignore_fixed=is_pure_baseline)
    step_results = []

    if is_pure_baseline:
        effective_policy = make_no_preference_policy()
        effective_cost_weights = base_cost_weights
    else:
        effective_policy = active_policy
        effective_cost_weights = cost_weights

    # Track cumulative physical bit usage so balanced_dynamic can avoid
    # creating additional overuse during the sequence.
    used_counts_so_far = {r: 0 for r in COUNT_LEVELS}

    for step, job_id in enumerate(sequence, start=1):
        row = pn_map[job_id]
        step_policy = get_step_policy(step, effective_policy, effective_cost_weights)
        step_phase = step_policy["step_phase"]
        prefer = step_policy.get("prefer", None)

        if policy_name == "efficiency_first":
            alloc = allocation_efficiency_first(row, rules)
        elif policy_name == "static_cost_first":
            alloc = allocation_static_cost_first(row, rules, base_cost_weights)
        elif policy_name == "dynamic_preference_greedy":
            alloc = allocation_dynamic_preference_greedy(row, rules, effective_cost_weights)
        elif policy_name in ["balanced_no_preference", "balanced_dynamic"]:
            opt_inv_weight = OPT_W_INVENTORY_OVERUSE if policy_name == "balanced_dynamic" else 0.0
            alloc = allocation_balanced_dynamic(
                row,
                rules,
                effective_cost_weights,
                effective_policy,
                policy_name,
                used_counts_before=used_counts_so_far,
                inventory_allowed_counts=inventory_allowed_counts,
                w_inventory_overuse_optimization=opt_inv_weight,
            )
        else:
            raise ValueError(f"Unknown policy_name: {policy_name}")

        result, _ = evaluate_pn_allocation(
            row=row,
            step=step,
            alloc=alloc,
            policy_name=policy_name,
            order_name=order_name,
            cost_weights=effective_cost_weights,
            w_change=step_policy["w_change"],
            w_cost=step_policy["w_cost"],
            w_due=step_policy["w_due"],
            w_capacity=step_policy["w_capacity"],
            w_quality=step_policy["w_quality"],
            step_phase=step_phase,
            preferred_regrind=prefer,
            rules=rules,
            use_due_priority=not is_pure_baseline,
            used_counts_before=used_counts_so_far,
            inventory_allowed_counts=inventory_allowed_counts,
            w_inventory_overuse_optimization=OPT_W_INVENTORY_OVERUSE if policy_name == "balanced_dynamic" else 0.0,
        )
        # Update cumulative usage for the next production step.
        for r in COUNT_LEVELS:
            used_counts_so_far[r] += int(result.get(f"{r}_count", 0))
            result[f"cumulative_used_{r}"] = int(used_counts_so_far[r])
            if inventory_allowed_counts is not None:
                result[f"inventory_allowed_{r}"] = int(inventory_allowed_counts.get(r, 0))
                result[f"cumulative_overuse_{r}"] = max(
                    0,
                    int(used_counts_so_far[r]) - int(inventory_allowed_counts.get(r, 0))
                )

        step_results.append(result)

    step_df = pd.DataFrame(step_results)

    total = {
        "order_name": order_name,
        "policy_name": policy_name,
        "sequence": " -> ".join(sequence),
        "active_daily_policy": str(active_policy.get("policy_name", "unknown")),
        "baseline_mode": "pure_no_preference" if is_pure_baseline else "priority_adjusted",
        "tool_change_count": int(step_df["tool_change_count"].sum()),
        "R0_count": int(step_df["R0_count"].sum()),
        "R1_count": int(step_df["R1_count"].sum()),
        "R2_count": int(step_df["R2_count"].sum()),
        "R3_count": int(step_df["R3_count"].sum()),
        "relative_cost_score": float(step_df["relative_cost_score"].sum()),
        "due_penalty": float(step_df["due_penalty"].sum()),
        "objective_score": float(step_df["objective_score"].sum()),
        "quality_violation_count": int(step_df["quality_violation_count"].sum()),
        "over_capacity_count": int(step_df["over_capacity_count"].sum()),
        "unmet_units": int(step_df["unmet_units"].sum()),
        "optimization_inventory_overuse_count": int(step_df.get("optimization_inventory_overuse_count", pd.Series([0])).sum()),
        "optimization_inventory_overuse_penalty": float(step_df.get("optimization_inventory_overuse_penalty", pd.Series([0.0])).sum()),
        "optimization_inventory_overuse_R0": int(step_df.get("optimization_inventory_overuse_R0", pd.Series([0])).sum()),
        "optimization_inventory_overuse_R1": int(step_df.get("optimization_inventory_overuse_R1", pd.Series([0])).sum()),
        "optimization_inventory_overuse_R2": int(step_df.get("optimization_inventory_overuse_R2", pd.Series([0])).sum()),
        "optimization_inventory_overuse_R3": int(step_df.get("optimization_inventory_overuse_R3", pd.Series([0])).sum()),
    }
    return total, step_df


def exhaustive_sequence_search(pn_df, policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts=None):
    ignore_fixed = policy_name == "balanced_no_preference"
    free_jobs = get_free_jobs_for_search(pn_df, ignore_fixed=ignore_fixed)
    best_total = None
    best_steps = None
    count = 0
    for seq_tuple in itertools.permutations(free_jobs):
        count += 1
        seq = make_sequence_from_free_order(pn_df, list(seq_tuple), ignore_fixed=ignore_fixed)
        total, steps = simulate_sequence(pn_df, seq, f"perm_{count}", policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)
        if best_total is None or total["objective_score"] < best_total["objective_score"]:
            best_total = total
            best_steps = steps
    best_total = dict(best_total)
    best_total["order_name"] = "exhaustive_best"
    best_steps = best_steps.copy()
    best_steps["order_name"] = "exhaustive_best"
    return best_total, best_steps


def random_sequence_search(pn_df, policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts=None, iterations=RANDOM_SEARCH_ITER, seed=RANDOM_SEED):
    rng = random.Random(seed)
    ignore_fixed = policy_name == "balanced_no_preference"
    free_jobs = get_free_jobs_for_search(pn_df, ignore_fixed=ignore_fixed)
    best_total = None
    best_steps = None
    for i in range(iterations):
        seq_free = free_jobs[:]
        rng.shuffle(seq_free)
        seq = make_sequence_from_free_order(pn_df, seq_free, ignore_fixed=ignore_fixed)
        total, steps = simulate_sequence(pn_df, seq, f"random_{i}", policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)
        if best_total is None or total["objective_score"] < best_total["objective_score"]:
            best_total = total
            best_steps = steps
    best_total = dict(best_total)
    best_total["order_name"] = "random_search_best"
    best_steps = best_steps.copy()
    best_steps["order_name"] = "random_search_best"
    return best_total, best_steps


def sa_sequence_search(pn_df, policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts=None, seed=RANDOM_SEED):
    rng = random.Random(seed)
    ignore_fixed = policy_name == "balanced_no_preference"
    free_jobs = get_free_jobs_for_search(pn_df, ignore_fixed=ignore_fixed)
    if len(free_jobs) <= 1:
        seq = make_sequence_from_free_order(pn_df, free_jobs, ignore_fixed=ignore_fixed)
        return simulate_sequence(pn_df, seq, "sa_sequence_best", policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)

    best_total = None
    best_steps = None
    for restart in range(SA_SEQUENCE_RESTARTS):
        cur_free = free_jobs[:]
        rng.shuffle(cur_free)
        cur_seq = make_sequence_from_free_order(pn_df, cur_free, ignore_fixed=ignore_fixed)
        cur_total, cur_steps = simulate_sequence(pn_df, cur_seq, f"sa_restart_{restart}", policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)
        cur_score = cur_total["objective_score"]

        if best_total is None or cur_score < best_total["objective_score"]:
            best_total = cur_total
            best_steps = cur_steps

        for step in range(SA_SEQUENCE_STEPS):
            t = step / max(1, SA_SEQUENCE_STEPS - 1)
            temp = SA_T0 * ((SA_T_END / SA_T0) ** t)
            new_free = cur_free[:]
            i, j = rng.sample(range(len(new_free)), 2)
            new_free[i], new_free[j] = new_free[j], new_free[i]
            new_seq = make_sequence_from_free_order(pn_df, new_free, ignore_fixed=ignore_fixed)
            new_total, new_steps = simulate_sequence(pn_df, new_seq, "sa_tmp", policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)
            new_score = new_total["objective_score"]
            if new_score <= cur_score:
                accept = True
            else:
                prob = math.exp(-(new_score - cur_score) / max(temp, 1e-12))
                accept = rng.random() < prob
            if accept:
                cur_free = new_free
                cur_total = new_total
                cur_steps = new_steps
                cur_score = new_score
            if cur_score < best_total["objective_score"]:
                best_total = cur_total
                best_steps = cur_steps

    best_total = dict(best_total)
    best_total["order_name"] = "sa_sequence_best"
    best_steps = best_steps.copy()
    best_steps["order_name"] = "sa_sequence_best"
    return best_total, best_steps


# ============================================================
# Common post-evaluation metrics
# ============================================================

def parse_sequence_string(sequence: str) -> List[str]:
    if not isinstance(sequence, str) or not sequence.strip():
        return []
    return [x.strip() for x in sequence.split("->") if x.strip()]


def common_due_penalty_from_sequence(sequence: str, pn_df: pd.DataFrame) -> float:
    priority_map = {str(row["job_id"]): int(row.get("due_priority", 0)) for _, row in pn_df.iterrows()}
    due = 0.0
    for step, job_id in enumerate(parse_sequence_string(sequence), start=1):
        due += priority_map.get(job_id, 0) * max(0, step - 1) * DUE_STEP_PENALTY_SCALE
    return float(due)


def inventory_overuse_from_counts(row: pd.Series, inventory_df: pd.DataFrame) -> Tuple[int, Dict[str, int]]:
    allowed_counts = build_inventory_allowed_counts(inventory_df)
    per_level: Dict[str, int] = {}
    total = 0
    for r in COUNT_LEVELS:
        used = int(row.get(f"{r}_count", 0))
        allowed = int(allowed_counts.get(r, 0))
        over = max(0, used - allowed)
        per_level[r] = int(over)
        total += int(over)
    return int(total), per_level

def add_common_evaluation_columns(summary_df, pn_df, inventory_df, base_cost_weights, dynamic_cost_weights):
    rows = []
    for _, row in summary_df.iterrows():
        out = row.to_dict()
        r_counts = {r: int(row.get(f"{r}_count", 0)) for r in COUNT_LEVELS}
        eval_base_cost = sum(base_cost_weights[r] * r_counts[r] for r in COUNT_LEVELS)
        eval_dynamic_cost = sum(dynamic_cost_weights[r] * r_counts[r] for r in COUNT_LEVELS)
        eval_due = common_due_penalty_from_sequence(str(row.get("sequence", "")), pn_df)
        over_total, over_by_level = inventory_overuse_from_counts(row, inventory_df)
        over_penalty = EVAL_W_INVENTORY_OVERUSE * over_total
        eval_base_score = EVAL_W_CHANGE * float(row.get("tool_change_count", 0)) + EVAL_W_COST * eval_base_cost
        eval_dynamic_score = EVAL_W_CHANGE * float(row.get("tool_change_count", 0)) + EVAL_W_COST * eval_dynamic_cost
        eval_practical_score = eval_dynamic_score + EVAL_W_DUE * eval_due + over_penalty
        out.update({
            "optimization_objective": float(row.get("objective_score", 0.0)),
            "eval_base_cost_score": float(eval_base_cost),
            "eval_dynamic_cost_score": float(eval_dynamic_cost),
            "eval_base_score": float(eval_base_score),
            "eval_dynamic_score": float(eval_dynamic_score),
            "eval_common_due_penalty": float(eval_due),
            "eval_inventory_overuse_count": int(over_total),
            "eval_inventory_overuse_penalty": float(over_penalty),
            "eval_inventory_overuse_R0": over_by_level["R0"],
            "eval_inventory_overuse_R1": over_by_level["R1"],
            "eval_inventory_overuse_R2": over_by_level["R2"],
            "eval_inventory_overuse_R3": over_by_level["R3"],
            "eval_practical_score": float(eval_practical_score),
        })
        rows.append(out)
    return pd.DataFrame(rows)


def build_common_evaluation_summary(best_df: pd.DataFrame) -> pd.DataFrame:
    cols = [
        "policy_name", "baseline_mode", "order_name", "sequence",
        "tool_change_count", "R0_count", "R1_count", "R2_count", "R3_count",
        "optimization_objective", "optimization_inventory_overuse_count", "optimization_inventory_overuse_penalty", "eval_base_score", "eval_dynamic_score",
        "eval_common_due_penalty", "eval_inventory_overuse_count",
        "eval_inventory_overuse_penalty", "eval_practical_score",
    ]
    keep = [c for c in cols if c in best_df.columns]
    return best_df[keep].sort_values("eval_practical_score").reset_index(drop=True)


# ============================================================
# Experiment and output
# ============================================================

def add_improvement_columns(summary_df: pd.DataFrame, baseline_order: str = "original_order") -> pd.DataFrame:
    rows = []
    for policy_name, sub in summary_df.groupby("policy_name"):
        best_obj = sub["objective_score"].min()
        best_change = sub["tool_change_count"].min()
        best_cost = sub["relative_cost_score"].min()
        baseline = sub[sub["order_name"] == baseline_order]
        base = baseline.iloc[0] if len(baseline) else sub.iloc[0]
        base_obj = base["objective_score"]
        base_change = base["tool_change_count"]
        base_cost = base["relative_cost_score"]
        for _, row in sub.iterrows():
            row = row.to_dict()
            row["objective_reduction_vs_original_pct"] = (base_obj - row["objective_score"]) / base_obj * 100.0 if base_obj else 0.0
            row["change_reduction_vs_original_pct"] = (base_change - row["tool_change_count"]) / base_change * 100.0 if base_change else 0.0
            row["cost_reduction_vs_original_pct"] = (base_cost - row["relative_cost_score"]) / base_cost * 100.0 if base_cost else 0.0
            row["objective_gap_to_best_pct"] = (row["objective_score"] - best_obj) / best_obj * 100.0 if best_obj else 0.0
            row["change_gap_to_best_pct"] = (row["tool_change_count"] - best_change) / best_change * 100.0 if best_change else 0.0
            row["cost_gap_to_best_pct"] = (row["relative_cost_score"] - best_cost) / best_cost * 100.0 if best_cost else 0.0
            rows.append(row)
    return pd.DataFrame(rows)


def choose_policy_best_row(sub: pd.DataFrame, policy_name: str) -> pd.Series:
    if policy_name == "balanced_no_preference":
        rank_map = {"exhaustive_best": 0, "random_search_best": 1, "sa_sequence_best": 2, "high_A_first": 3, "high_C_first": 4, "high_C_last": 5, "original_order": 6}
    else:
        rank_map = {"exhaustive_best": 0, "random_search_best": 1, "sa_sequence_best": 2, "due_priority_first": 3, "fixed_sequence_candidate": 4, "original_order": 5, "high_A_first": 6, "high_C_first": 7, "high_C_last": 8}
    tmp = sub.copy()
    tmp["_best_row_rank"] = tmp["order_name"].map(rank_map).fillna(99)
    # objective_score already includes optimization_inventory_overuse_penalty
    # for balanced_dynamic. Add optimization overuse as an explicit tie-breaker
    # so the selected row is always the most inventory-feasible among equal scores.
    sort_cols = [
        "objective_score",
        "optimization_inventory_overuse_count" if "optimization_inventory_overuse_count" in tmp.columns else "_best_row_rank",
        "_best_row_rank",
        "tool_change_count",
        "relative_cost_score",
    ]
    # Remove duplicate columns while preserving order.
    sort_cols = list(dict.fromkeys(sort_cols))
    tmp = tmp.sort_values(sort_cols)
    return tmp.iloc[0].drop(labels=["_best_row_rank"])


def make_inventory_usage_summary(best_steps: pd.DataFrame, inventory_df: pd.DataFrame) -> pd.DataFrame:
    usage = {r: int(best_steps[f"{r}_count"].sum()) for r in COUNT_LEVELS}
    allowed_counts = build_inventory_allowed_counts(inventory_df)
    rows = []
    for r in COUNT_LEVELS:
        inv = inventory_row_for_count_level(inventory_df, r)
        available = int(inv.get("available_count", 0))
        reserve = int(inv.get("min_reserve_count", 0))
        used = usage[r]
        after = available - used
        allowed = int(allowed_counts.get(r, 0))
        rows.append({
            "count_level": r,
            "source_inventory_level": "R0E" if r == "R0" else r,
            "available_count": available,
            "allowed_count_after_reserve": allowed,
            "used_count_estimate": used,
            "remaining_count_estimate": after,
            "min_reserve_count": reserve,
            "below_reserve_after_run": int(after < reserve),
            "over_allowed_count": max(0, used - allowed),
        })
    return pd.DataFrame(rows)

def run_experiment(production_path, inventory_path, policy_path, rule_path, output_dir=OUTPUT_DIR):
    output_dir.mkdir(parents=True, exist_ok=True)

    plan_df = load_production_plan(production_path)
    inventory_df = load_inventory(inventory_path)
    active_policy = load_daily_policy(policy_path)
    rules, rules_df = load_hole_regrind_rules(rule_path)

    global CAP_UNITS
    CAP_UNITS = build_capacity_units(inventory_df)

    pn_df = prepare_pn_table_from_df(plan_df)
    cost_weights, cost_df = build_dynamic_cost_weights(inventory_df, active_policy)
    base_cost_weights = build_base_cost_weights(inventory_df)
    inventory_allowed_counts = build_inventory_allowed_counts(inventory_df)

    plan_df.to_csv(output_dir / "loaded_production_plan.csv", index=False, encoding="utf-8-sig")
    inventory_df.to_csv(output_dir / "loaded_drill_inventory.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame([active_policy.to_dict()]).to_csv(output_dir / "loaded_daily_policy.csv", index=False, encoding="utf-8-sig")
    rules_df.to_csv(output_dir / "loaded_hole_regrind_rule.csv", index=False, encoding="utf-8-sig")
    cost_df.to_csv(output_dir / "dynamic_cost_weights.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame([{"regrind_level": k, "capacity_units": v, "capacity_hits": v * UNIT_HITS} for k, v in CAP_UNITS.items()]).to_csv(
        output_dir / "drill_capacity_units.csv",
        index=False,
        encoding="utf-8-sig",
    )
    pd.DataFrame([{"count_level": k, "allowed_count_after_reserve": v} for k, v in inventory_allowed_counts.items()]).to_csv(
        output_dir / "inventory_allowed_counts.csv",
        index=False,
        encoding="utf-8-sig",
    )
    pd.DataFrame([{"regrind_level": k, "base_cost_weight_for_no_preference": v} for k, v in base_cost_weights.items()]).to_csv(output_dir / "base_cost_weights_no_preference.csv", index=False, encoding="utf-8-sig")
    pn_df.to_csv(output_dir / "pn_input_prepared.csv", index=False, encoding="utf-8-sig")

    priority_sequence_candidates = {
        "original_order": get_original_sequence(pn_df),
        "due_priority_first": get_due_priority_first_sequence(pn_df),
        "fixed_sequence_candidate": get_fixed_sequence_candidate(pn_df),
        "high_A_first": get_high_A_first_sequence(pn_df),
        "high_C_first": get_high_C_first_sequence(pn_df),
        "high_C_last": get_high_C_last_sequence(pn_df),
    }
    pure_baseline_sequence_candidates = {
        "original_order": get_original_sequence(pn_df),
        "high_A_first": get_high_A_first_sequence(pn_df),
        "high_C_first": get_high_C_first_sequence(pn_df),
        "high_C_last": get_high_C_last_sequence(pn_df),
    }
    policies = ["efficiency_first", "static_cost_first", "dynamic_preference_greedy", "balanced_no_preference", "balanced_dynamic"]

    all_totals = []
    all_steps = []

    print("\nActive daily policy:", active_policy.get("policy_name", "unknown"))
    print("Dynamic cost weights:", cost_weights)
    print("CSV-driven capacity units:", CAP_UNITS)
    print("Base cost weights for balanced_no_preference:", base_cost_weights)
    print("Hole/regrind rules:", rules)

    for policy_name in policies:
        print(f"\n===== Policy: {policy_name} =====")
        sequence_candidates = pure_baseline_sequence_candidates if policy_name == "balanced_no_preference" else priority_sequence_candidates
        for order_name, seq in sequence_candidates.items():
            total, steps = simulate_sequence(pn_df, seq, order_name, policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)
            all_totals.append(total)
            all_steps.append(steps)
            print(f"{order_name:25s} changes={total['tool_change_count']:8d} R0={total['R0_count']:6d} R1={total['R1_count']:6d} R2={total['R2_count']:6d} R3={total['R3_count']:6d} due={total['due_penalty']:10.2f} cost={total['relative_cost_score']:10.2f} obj={total['objective_score']:10.2f}")

        ignore_fixed_for_search = policy_name == "balanced_no_preference"
        free_jobs = get_free_jobs_for_search(pn_df, ignore_fixed=ignore_fixed_for_search)
        if len(free_jobs) <= MAX_EXHAUSTIVE_PN_COUNT:
            t0 = time.perf_counter()
            best_total, best_steps = exhaustive_sequence_search(pn_df, policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)
            best_total["runtime_sec"] = time.perf_counter() - t0
            all_totals.append(best_total)
            all_steps.append(best_steps)
            print(f"{'exhaustive_best':25s} changes={best_total['tool_change_count']:8d} R0={best_total['R0_count']:6d} R1={best_total['R1_count']:6d} R2={best_total['R2_count']:6d} R3={best_total['R3_count']:6d} due={best_total['due_penalty']:10.2f} cost={best_total['relative_cost_score']:10.2f} obj={best_total['objective_score']:10.2f} time={best_total['runtime_sec']:.3f}s")
        else:
            t0 = time.perf_counter()
            best_total, best_steps = random_sequence_search(pn_df, policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)
            best_total["runtime_sec"] = time.perf_counter() - t0
            all_totals.append(best_total)
            all_steps.append(best_steps)

        t0 = time.perf_counter()
        sa_total, sa_steps = sa_sequence_search(pn_df, policy_name, active_policy, cost_weights, base_cost_weights, rules, inventory_allowed_counts)
        sa_total["runtime_sec"] = time.perf_counter() - t0
        all_totals.append(sa_total)
        all_steps.append(sa_steps)
        print(f"{'sa_sequence_best':25s} changes={sa_total['tool_change_count']:8d} R0={sa_total['R0_count']:6d} R1={sa_total['R1_count']:6d} R2={sa_total['R2_count']:6d} R3={sa_total['R3_count']:6d} due={sa_total['due_penalty']:10.2f} cost={sa_total['relative_cost_score']:10.2f} obj={sa_total['objective_score']:10.2f} time={sa_total['runtime_sec']:.3f}s")

    summary_df = pd.DataFrame(all_totals)
    summary_df = add_common_evaluation_columns(summary_df, pn_df, inventory_df, base_cost_weights, cost_weights)
    summary_df = add_improvement_columns(summary_df, baseline_order="original_order")
    steps_df = pd.concat(all_steps, ignore_index=True)

    best_rows = []
    for policy_name, sub in summary_df.groupby("policy_name"):
        best_rows.append(choose_policy_best_row(sub, policy_name))
    best_df = pd.DataFrame(best_rows)
    common_eval_df = build_common_evaluation_summary(best_df)

    summary_df.to_csv(output_dir / "sequence_summary.csv", index=False, encoding="utf-8-sig")
    steps_df.to_csv(output_dir / "sequence_step_results.csv", index=False, encoding="utf-8-sig")
    best_df.to_csv(output_dir / "best_sequence_summary.csv", index=False, encoding="utf-8-sig")
    common_eval_df.to_csv(output_dir / "common_evaluation_summary.csv", index=False, encoding="utf-8-sig")

    best_balanced = summary_df[summary_df["policy_name"] == "balanced_dynamic"].sort_values("objective_score").head(1)
    if len(best_balanced):
        best_policy = "balanced_dynamic"
        best_order = best_balanced.iloc[0]["order_name"]
    else:
        global_best = summary_df.sort_values("objective_score").iloc[0]
        best_policy = global_best["policy_name"]
        best_order = global_best["order_name"]
    best_steps = steps_df[(steps_df["policy_name"] == best_policy) & (steps_df["order_name"] == best_order)]
    inv_usage = make_inventory_usage_summary(best_steps, inventory_df)
    inv_usage.to_csv(output_dir / "inventory_usage_summary.csv", index=False, encoding="utf-8-sig")

    return pn_df, summary_df, steps_df


# ============================================================
# Main
# ============================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="CSV-driven PCB drill-bit allocation with hole/regrind rule CSV")
    parser.add_argument("--production", type=Path, default=resolve_default_path("production_plan_template.csv"))
    parser.add_argument("--inventory", type=Path, default=resolve_default_path("drill_inventory_template_corrected.csv"))
    parser.add_argument("--policy", type=Path, default=resolve_default_path("daily_policy_template.csv"))
    parser.add_argument("--rules", type=Path, default=resolve_default_path("hole_regrind_rule_template.csv"))
    parser.add_argument("--output", type=Path, default=OUTPUT_DIR)
    return parser.parse_args()


def main():
    args = parse_args()
    print("PCB Drill-Bit CSV-Driven Dynamic Inventory Preference Test with Hole Rules")
    print("==========================================================================")
    print(f"UNIT_HITS = {UNIT_HITS}")
    print(f"CAP_UNITS = {CAP_UNITS}")
    print(f"SCRIPT_DIR = {SCRIPT_DIR}")
    print(f"DEFAULT_TEMPLATE_DIR = {DEFAULT_TEMPLATE_DIR}")
    print(f"Production CSV = {args.production}")
    print(f"Inventory CSV  = {args.inventory}")
    print(f"Policy CSV     = {args.policy}")
    print(f"Rules CSV      = {args.rules}")
    print(f"Output DIR     = {args.output}")

    run_experiment(args.production, args.inventory, args.policy, args.rules, args.output)

    print("\nDone.")
    print(f"Prepared PN input:       {args.output / 'pn_input_prepared.csv'}")
    print(f"Loaded hole rules:       {args.output / 'loaded_hole_regrind_rule.csv'}")
    print(f"Dynamic cost weights:    {args.output / 'dynamic_cost_weights.csv'}")
    print(f"Drill capacity units:    {args.output / 'drill_capacity_units.csv'}")
    print(f"Sequence summary:        {args.output / 'sequence_summary.csv'}")
    print(f"Step results:            {args.output / 'sequence_step_results.csv'}")
    print(f"Common evaluation:       {args.output / 'common_evaluation_summary.csv'}")
    print("\nKey comparison:")
    print("  drill_inventory_template_corrected.csv controls capacity_hits for R0E/R0N/R1/R2/R3.")
    print("  hole_regrind_rule_template.csv controls which regrind levels each hole type may use.")
    print("  balanced_no_preference = pure baseline with the same hole rules but no priority/preference.")
    print("  balanced_dynamic = priority-adjusted search with dynamic inventory cost and active inventory-overuse avoidance.")
    print(f"  OPT_W_INVENTORY_OVERUSE = {OPT_W_INVENTORY_OVERUSE} (large value means inventory overuse is strongly avoided during optimization)")


if __name__ == "__main__":
    main()
